const roles = {
  admin: [
    "dashboard",
    "products",
    "products/new",
    "categories",
    "brands",
    "orders",
    "sales-returns",
    "invoices",
    "accounts/invites",
    "accounts/users",
    "accounts/customers",
    "reports/sales",
    "reports/inventory",
    "reports/profit-loss",
    "reports/annual",
    "user/profile",
    "user/security",
    "user/activities",
  ],
  moderator: [
    "dashboard",
    "products",
    "categories",
    "orders",
    "sales-returns",
    "invoices",
    "reports/sales",
    "reports/inventory",
    "user/profile",
    "user/security",
    "user/activities",
  ],
  editor: [
    "dashboard",
    "products",
    "products/new",
    "categories",
    "brands",
    "orders",
    "sales-returns",
    "user/profile",
    "user/security",
    "user/activities",
  ],
};

export default roles;
